sudo: required
dist: trusty
language: python
python: "3.5"
install:
  - "sudo pip install ansible"
script:
  - "sudo mkdir -p /var/www"
  - "sudo ln -s `pwd` /var/www/obo-purls"
  - "cd tools"
  - "echo 'localhost' > hosts"
  - "ansible-playbook -i hosts -e 'mode=travis' --connection=local site.yml"
  - "cd .."
  - "sudo make all test"
notifications:
  email:
    - james@overton.ca
#   - cjmungall@lbl.gov
#   - sjcarbon@lbl.gov
