# PURL configuration for http://purl.obolibrary.org/obo/aeo

idspace: AEO
base_url: /obo/aeo

products:
- aeo.owl: http://ontologies.berkeleybop.org/aeo.owl
- aeo.obo: http://ontologies.berkeleybop.org/aeo.obo

term_browser: ontobee
example_terms:
- AEO_0000095

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=AEO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/AEO_0000095
    to: http://www.ontobee.org/browser/rdf.php?o=AEO&iri=http://purl.obolibrary.org/obo/AEO_0000095

