# PURL configuration for http://purl.obolibrary.org/obo/aero

idspace: AERO
base_url: /obo/aero

base_redirect: https://github.com/mcourtot/adverse-event-reporting-ontology/tree/master/src/ontology

products:
- aero.owl: https://raw.githubusercontent.com/mcourtot/adverse-event-reporting-ontology/master/src/ontology/aero.owl

term_browser: ontobee
example_terms:
- AERO_0000001

entries:
- exact: /external.owl
  replacement: https://raw.githubusercontent.com/mcourtot/adverse-event-reporting-ontology/master/src/ontology/external.owl

- exact: /externalDerived.owl
  replacement: https://raw.githubusercontent.com/mcourtot/adverse-event-reporting-ontology/master/src/ontology/externalDerived.owl

- exact: /external-by-hand.owl
  replacement: https://raw.githubusercontent.com/mcourtot/adverse-event-reporting-ontology/master/src/ontology/external-by-hand.owl

- exact: /tracker
  replacement: https://github.com/mcourtot/adverse-event-reporting-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=AERO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/AERO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=AERO&iri=http://purl.obolibrary.org/obo/AERO_0000001

