# PURL configuration for http://purl.obolibrary.org/obo/apo

idspace: APO
base_url: /obo/apo

products:
- apo.owl: http://ontologies.berkeleybop.org/apo.owl
- apo.obo: http://ontologies.berkeleybop.org/apo.obo

term_browser: ontobee
example_terms:
- APO_0000018

entries:
- prefix: /
  replacement: https://github.com/cmungall/phenotype_ontologies/raw/master/apo/
