# PURL configuration for http://purl.obolibrary.org/obo/bco

idspace: BCO
base_url: /obo/bco

products:
- bco.owl: https://raw.githubusercontent.com/BiodiversityOntologies/bco/master/releases/2015-04-10/bco.owl

term_browser: ontobee
example_terms:
- BCO_0000000

entries:
- exact: /bco-non-classified.owl
  replacement: https://raw.githubusercontent.com/BiodiversityOntologies/bco/master/releases/2015-04-10/bco-non-classified.owl

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=BCO&iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://raw.githubusercontent.com/BiodiversityOntologies/bco/master/
