# PURL configuration for http://purl.obolibrary.org/obo/caro

idspace: CARO
base_url: /obo/caro

products:
- caro.owl: http://ontologies.berkeleybop.org/caro.owl

term_browser: ontobee
example_terms:
- CARO_0000000

entries:
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/caro/master/src/ontology/

