# PURL configuration for http://purl.obolibrary.org/obo/cdno

idspace: CDNO
base_url: /obo/cdno

products:
- cdno.owl: https://raw.githubusercontent.com/CompositionalDietaryNutritionOntology/cdno/master/cdno.owl
- cdno.obo: https://raw.githubusercontent.com/CompositionalDietaryNutritionOntology/cdno/master/cdno.obo

term_browser: ontobee
example_terms:
- CDNO_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/CompositionalDietaryNutritionOntology/cdno/v

- prefix: /tracker/
  replacement: https://github.com/CompositionalDietaryNutritionOntology/cdno/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/CDNO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/CompositionalDietaryNutritionOntology/cdno/master/
