idspace: CHEMINFO
base_url: /obo/cheminf

products:
- cheminf.owl: https://raw.githubusercontent.com/semanticchemistry/semanticchemistry/master/ontology/cheminf.owl
- cheminf.obo: http://ontologies.berkeleybop.org/cheminf.obo

term_browser: ontobee
