# PURL configuration for http://purl.obolibrary.org/obo/chmo

idspace: CHMO
base_url: /obo/chmo

products:
- chmo.owl: https://raw.githubusercontent.com/rsc-ontologies/rsc-cmo/master/chmo.owl
- chmo.obo: https://raw.githubusercontent.com/rsc-ontologies/rsc-cmo/master/chmo.obo

term_browser: ontobee
example_terms:
- CHMO_0002748
