# PURL configuration for http://purl.obolibrary.org/obo/cio

idspace: CIO
base_url: /obo/cio

products:
- cio.owl: https://raw.githubusercontent.com/BgeeDB/confidence-information-ontology/master/src/ontology/cio.owl
- cio.obo: https://raw.githubusercontent.com/BgeeDB/confidence-information-ontology/master/src/ontology/cio-simple.obo

term_browser: ontobee
