####
#### Use kwalify and this schema to validate the config files.
#### Example:
####    kwalify -E -m cofig.schema.yaml
####    kwalify -E -f ./metadata/db-xrefs.schema.yaml ./metadata/db-xrefs.yaml
####
type: map
mapping:
  "description":
    type: str
    required: false
  "entries":
    type: seq
    required: true
    sequence:
      - type: map
        mapping:
          "exact":
            type: str
            pattern: /^\//
            required: false
            unique: true
          "prefix":
            type: str
            pattern: /^\//
            required: false
            unique: true
          "regex":
            type: str
            required: false
            unique: true
          "replacement":
            type: str
            pattern: /^https?\:\/\/.+/
            required: true
            unique: false
