# PURL configuration for http://purl.obolibrary.org/obo/dideo

idspace: DIDEO
base_url: /obo/dideo

products:
- dideo.owl: https://raw.githubusercontent.com/DIDEO/DIDEO/master/ontology_release/dideo.owl

term_browser: ontobee
example_terms:
- DIDEO_00000001

entries:
- exact: /iswcTest/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/master/Dideo_ISWC_Test.owl
  
- exact: /2016-05-12/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/2016-05-12/dideo.owl
  
- exact: /2016-07-06/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/2016-07-06/ontology%20releases/dideo.owl
  
- exact: /2016-07-07/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/2017-07-07/ontology_release/dideo.owl

- exact: /EvidenceTypes/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/master/evidence_types_test.owl
  
- exact: /dev/dideo.owl
  replacement: https://raw.githubusercontent.com/DIDEO/DIDEO/master/dideo.owl
