# PURL configuration for http://purl.obolibrary.org/obo/eco

id: ECO
base_url: /obo/eco

products:
- eco.owl: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.owl
- eco.obo: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/eco.obo

term_browser: ontobee
example_terms:
- ECO_0000000

entries:
- exact: /lagacy
  replacement: http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/evidence_code.obo?view=log

- exact: /legacy
  replacement: http://obo.cvs.sourceforge.net/viewvc/obo/obo/ontology/evidence_code.obo?view=log

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/evidenceontology/evidenceontology/v

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=ECO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/ECO_0000000
    to: http://www.ontobee.org/browser/rdf.php?o=ECO&iri=http://purl.obolibrary.org/obo/ECO_0000000

- prefix: /
  replacement: https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/

