# PURL configuration for http://purl.obolibrary.org/obo/ehdaa2

id: EHDAA2
base_url: /obo/ehdaa2

products:
- ehdaa2.owl: http://www.berkeleybop.org/ontologies/ehdaa2.owl
- ehdaa2.obo: http://www.berkeleybop.org/ontologies/ehdaa2.obo

term_browser: ontobee
example_terms:
- EHDAA2_0000000

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=EHDAA2&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/EHDAA2_0000000
    to: http://www.ontobee.org/browser/rdf.php?o=EHDAA2&iri=http://purl.obolibrary.org/obo/EHDAA2_0000000

