idspace: EPIO
base_url: /obo/epio

products:
- epso.owl: https://raw.githubusercontent.com/SCAI-BIO/EpilepsyOntology/main/release/EPIO_merged.owl


term_browser: ontobee

example_terms:
- EPIO_0000011

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/SCAI-BIO/EpilepsyOntology/main/release
  

- prefix: /tracker/
  replacement: https://github.com/SCAI-BIO/EpilepsyOntology/issues


## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/SCAI-BIO/EpilepsyOntology/main/
