# PURL configuration for http://purl.obolibrary.org/obo/exo

id: ExO
base_url: /obo/exo

products:
- exo.owl: http://www.berkeleybop.org/ontologies/exo.owl

term_browser: ontobee
example_terms:
- ExO_0000000
