# PURL configuration for http://purl.obolibrary.org/obo/fbcv

idspace: FBcv
base_url: /obo/fbcv

base_redirect: https://github.com/FlyBase/flybase-controlled-vocabulary/wiki

products:
- fbcv.owl: https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/fbcv.owl
- fbcv.obo: https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/fbcv.obo

term_browser: ontobee
example_terms:
- FBcv_0000000

entries:
- exact: /tracker
  replacement: https://github.com/FlyBase/flybase-controlled-vocabulary/issues

- exact: /downloads
  replacement: https://github.com/FlyBase/flybase-controlled-vocabulary/wiki

- exact: /fbcv-flybase.obo
  replacement: https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/fbcv-flybase.obo

- exact: /releases/
  replacement: https://github.com/FlyBase/flybase-controlled-vocabulary/tree/master/releases

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=FBcv&iri=http://purl.obolibrary.org/obo/

- prefix: /wiki/
  replacement: https://github.com/FlyBase/flybase-controlled-vocabulary/wiki

- prefix: /
  replacement: https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/

