# PURL configuration for http://purl.obolibrary.org/obo/fbdv

idspace: FBdv
base_url: /obo/fbdv

base_redirect: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki

products:
- fbdv.owl: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/releases/fbdv.owl
- fbdv.obo: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/releases/fbdv.obo

term_browser: ontobee
example_terms:
- FBdv_00005370

entries:
- exact: /tracker
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/issues

- exact: /downloads
  replacement: https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/wiki/Download-guide

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=FBdv&iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://raw.githubusercontent.com/FlyBase/drosophila-anatomy-developmental-ontology/master/fbdv/releases/

