# PURL configuration for http://purl.obolibrary.org/obo/fix

idspace: FIX
base_url: /obo/fix

products:
- fix.obo: ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/fix.obo
- fix.owl: http://ontologies.berkeleybop.org/fix.owl

term_browser: ontobee
example_terms:
- FIX_0000000
