# PURL configuration for http://purl.obolibrary.org/obo/fypo

idspace: FYPO
base_url: /obo/fypo

products:
- fypo.owl: https://github.com/pombase/fypo/releases/latest/download/fypo.owl
- fypo.obo: https://github.com/pombase/fypo/releases/latest/download/fypo.obo
- fypo.json: https://github.com/pombase/fypo/releases/latest/download/fypo.json

term_browser: ontobee
example_terms:
- FYPO_0000001

entries:

- prefix: /releases/
  replacement: https://github.com/pombase/fypo/releases/download/v

- prefix: /tracker/
  replacement: https://github.com/pombase/fypo/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/FYPO?iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://github.com/pombase/fypo/releases/latest/download/
