# PURL configuration for http://purl.obolibrary.org/obo/gaz

idspace: GAZ
base_url: /obo/gaz

products:
- gaz.owl: https://zenodo.org/records/18247183/files/gaz.owl?download=1
- gaz.obo: https://zenodo.org/records/18247183/files/gaz.obo?download=1

entries:
- exact: /gaz-countries.owl
  replacement: https://raw.githubusercontent.com/EnvironmentOntology/gaz/master/src/ontology/gaz_countries.owl

term_browser: ontobee
example_terms:
- GAZ_00002560
