# PURL configuration for http://purl.obolibrary.org/obo/gno

idspace: GNO
base_url: /obo/gno

products:
- gno.owl: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.owl
- gno.obo: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.obo
- gno.json: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.json

term_browser: custom
example_terms:
  - GNO_G24005JZ

entries:
  - exact: /2020-03-20/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.0/GNOme.owl

  - exact: /2020-03-23/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.1/GNOme.owl
    
  - exact: /2020-04-14/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.2/GNOme.owl
    
  - exact: /2020-05-08/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.3/GNOme.owl
 
  - exact: /2020-06-10/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.4/GNOme.owl
    
  - exact: /2020-06-12/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.5.5/GNOme.owl
    
  - exact: /2020-09-23/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.6.0/GNOme.owl

  - exact: /2020-09-28/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.6.1/GNOme.owl

  - exact: /2020-10-01/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.6.2/GNOme.owl

  - exact: /2020-10-14/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.6.3/GNOme.owl

  - exact: /2021-03-05/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.7.0/GNOme.owl

  - exact: /2021-05-12/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.7.1/GNOme.owl

  - exact: /2021-06-16/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.7.2/GNOme.owl
    
  - exact: /2021-07-28/gno.owl
    replacement: https://github.com/glygen-glycan-data/GNOme/releases/download/V1.8.0/GNOme.owl
