# PURL configuration for http://purl.obolibrary.org/obo/gno

idspace: GNO
base_url: /obo/gno

products:
- gno.owl: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.owl
- gno.obo: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.obo
- gno.json: https://github.com/glygen-glycan-data/GNOme/releases/latest/download/GNOme.json

term_browser: ontobee
example_terms:
- GNO_10000019
