# PURL configuration for http://purl.obolibrary.org/obo/go

idspace: GO
base_url: /obo/go

products:
- go.owl: http://current.geneontology.org/ontology/go.owl
- go.obo: http://current.geneontology.org/ontology/go.obo
- go.json: http://current.geneontology.org/ontology/go.json

term_browser: custom
example_terms:
- GO_0006915

entries:

- exact: /go.obo
  replacement: http://current.geneontology.org/ontology/go.obo

- exact: /go.owl
  replacement: http://current.geneontology.org/ontology/go.owl

## User and group metadata for GO-CAM model metadata resolution.
- exact: /metadata/users.ttl
  replacement: http://experimental.geneontology.io/metadata/users.ttl
- exact: /metadata/groups.ttl
  replacement: http://experimental.geneontology.io/metadata/groups.ttl

- exact: /tracker
  replacement: https://github.com/geneontology/go-ontology/issues

- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/geneontology/go-ontology/master/src/design_patterns/
  tests:
  - from: /patterns/regulation.yaml
    to: https://raw.githubusercontent.com/geneontology/go-ontology/master/src/design_patterns/regulation.yaml

- prefix: /experimental/
  replacement: http://geneontology.org/experimental/

## the noctua ontology does not fit in the main GO SVN space, use a Jenkins artefact for now
## see https://github.com/geneontology/neo/issues/5
- prefix: /noctua/
  replacement: http://build-artifacts.berkeleybop.org/build-noctua-entity-ontology/latest/

- prefix: /noctua-obo/
  replacement: http://build-artifacts.berkeleybop.org/build-noctua-obo-ontology/latest/

- prefix: /snapshot/
  replacement: http://snapshot.geneontology.org/ontology/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=GO&iri=http://purl.obolibrary.org/obo/

# These release IRIs were published with incorrect dates due to a timezone issue in Docker
- prefix: /releases/2019-03-19/
  replacement: http://release.geneontology.org/2019-03-18/ontology/
  
- prefix: /releases/2019-06-10/
  replacement: http://release.geneontology.org/2019-06-09/ontology/

- regex: ^/obo/go/releases/([^\s/]+)/(\S+)$
  replacement: http://release.geneontology.org/$1/ontology/$2
  tests:
  - from: /releases/2019-01-01/go.owl
    to: http://release.geneontology.org/2019-01-01/ontology/go.owl
  - from: /releases/2019-01-01/extensions/go-plus.owl
    to: http://release.geneontology.org/2019-01-01/ontology/extensions/go-plus.owl

  # Terms for GO REFs
# http://purl.obolibrary.org/obo/go/references/0000001
# should point to
# https://geneontology.org/GO_REF/0000001
- regex: ^/obo/go/references/(\d+)$
  replacement: https://geneontology.org/GO_REF/$1
  tests:
  - from: /references/0000001
    to: https://geneontology.org/GO_REF/0000001

# Keep this as last entry as the rules are matched in order
- prefix: /
  replacement: http://current.geneontology.org/ontology/
  
