# PURL configuration for http://purl.obolibrary.org/obo/go

idspace: GO
base_url: /obo/go

products:
- go.owl: http://geneontology.org/ontology/go.owl
- go.obo: http://geneontology.org/ontology/go.obo

term_browser: ontobee
example_terms:
- GO_0000001

entries:
- exact: /go.obo
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/go.obo

- exact: /go.owl
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/go.owl

- exact: /tracker
  replacement: https://github.com/geneontology/go-ontology/issues

- prefix: /experimental/
  replacement: http://geneontology.org/experimental/

## the noctua ontology does not fit in the main GO SVN space, use a Jenkins artefact for now
## see https://github.com/geneontology/neo/issues/5
- prefix: /noctua/
  replacement: http://build-artifacts.berkeleybop.org/build-noctua-entity-ontology/latest/

- prefix: /noctua-obo/
  replacement: http://build-artifacts.berkeleybop.org/build-noctua-obo-ontology/latest/

- prefix: /releases/
  replacement: http://viewvc.geneontology.org/viewvc/GO-SVN/ontology-releases/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=GO&iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: http://geneontology.org/ontology/
  
# Terms for GO REFs
# https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000001.md
# should point to
# http://purl.obolibrary.org/obo/go/references/0000001
- regex: ^/obo/go/references/(\d+)$
  replacement: https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-$1.md
  tests:
  - from: /references/0000001
    to: https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000001.md

