# PURL configuration for http://purl.obolibrary.org/obo/hancestro

idspace: HANCESTRO
base_url: /obo/hancestro

products:
- hancestro.owl: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro.owl

term_browser: ontobee
example_terms:
- HANCESTRO_0004

entries:
- exact: /hancestro.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro.owl
- exact: /hancestro-base.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro-base.owl
- exact: /hancestro-full.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro-full.owl
- exact: /hancestro_inferred.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro.owl
- exact: /hancestro_bfo.owl
  replacement: https://raw.githubusercontent.com/EBISPOT/hancestro/main/hancestro-full.owl
  
  
