# PURL configuration for http://purl.obolibrary.org/obo/hao

idspace: HAO
base_url: /obo/hao

base_redirect: http://hymao.org/

products:
- hao.owl: https://raw.githubusercontent.com/hymao/hao/master/hao.owl
- hao.obo: https://raw.githubusercontent.com/hymao/hao/master/hao.obo
- depictions.owl: https://raw.githubusercontent.com/hymao/hao/master/depictions.owl
- arthropod-mappings.obo: https://raw.githubusercontent.com/hymao/hao/master/arthropod-mappings.obo

term_browser: custom

entries:
- exact: /wiki
  replacement: http://hymao.org/

- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=HAO

- prefix: /about/
  replacement: http://api.hymao.org/api/ontology/ontology_class/
  tests:
  - from: /about/HAO_0000000
    to: http://api.hymao.org/api/ontology/ontology_class/HAO_0000000

- prefix: /
  replacement: https://raw.githubusercontent.com/hymao/hao/v
