# PURL configuration for http://purl.obolibrary.org/obo/hp

idspace: HP
base_url: /obo/hp

base_redirect: https://github.com/obophenotype/human-phenotype-ontology

products:
- hp.owl: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.owl
- hp.obo: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.obo
- hp.json: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.json

term_browser: custom

entries:
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/v

- prefix: /tracker
  replacement: https://github.com/obophenotype/human-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/HP_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=HP&iri=http://purl.obolibrary.org/obo/HP_0000001

# HPOA files
- exact: /hpoa/phenotype_annotation.tab
  replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation.tab

- exact: /hpoa/phenotype_annotation_negated.tab
  replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_annotation_negated.tab

- exact: /hpoa/genes_to_phenotype.txt
  replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/genes_to_phenotype.txt

- exact: /hpoa/phenotype_to_genes.txt
  replacement: http://compbio.charite.de/jenkins/job/hpo.annotations/lastSuccessfulBuild/artifact/misc/phenotype_to_genes.txt

- exact: /hpoa/phenotype.hpoa
  replacement: http://compbio.charite.de/jenkins/job/hpo.annotations.current/lastSuccessfulBuild/artifact/current/phenotype.hpoa


# default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/
