# PURL configuration for http://purl.obolibrary.org/obo/ico

idspace: ICO
base_url: /obo/ico

products:
- ico.owl: http://ico-ontology.googlecode.com/svn/trunk/src/ontology/ico_merged.owl

term_browser: ontobee
example_terms:
- ICO_0000001
