# PURL configuration for http://purl.obolibrary.org/obo/ma

idspace: MA
base_url: /obo/ma

products:
- ma.owl: https://raw.githubusercontent.com/obophenotype/adult-mouse-anatomy-ontology/refs/heads/main/ma.owl
- ma.obo: https://raw.githubusercontent.com/obophenotype/adult-mouse-anatomy-ontology/refs/heads/main/ma.obo

term_browser: ontobee
example_terms:
- MA_0000001
