# PURL configuration for http://purl.obolibrary.org/obo/mat

idspace: MAT
base_url: /obo/mat

products:
- mat.owl: http://www.berkeleybop.org/ontologies/mat.owl
- mat.obo: http://www.berkeleybop.org/ontologies/mat.obo

term_browser: ontobee
example_terms:
- MAT_0000000
