# PURL configuration for http://purl.obolibrary.org/obo/mf

idspace: MF
base_url: /obo/mf

products:
- mf.owl: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/MF.owl

term_browser: ontobee
example_terms:
- MF_0000000

entries:
- exact: /external/GO_import.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/GO_import.owl

- exact: /internal/MF-core.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/internal/MF-core.owl

- exact: /internal/MD-core.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/internal/MD-core.owl

- exact: /external/ontology-metadata-slim.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/ontology-metadata-slim.owl

- exact: /external/behavior-slim.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/behavior-slim.owl

- exact: /external/bfo-properties-slim.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/bfo-properties-slim.owl

- exact: /external/doid-slim.owl
  replacement: https://raw.githubusercontent.com/jannahastings/mental-functioning-ontology/master/ontology/external/doid-slim.owl
