# PURL configuration for http://purl.obolibrary.org/obo/mfoem

idspace: MFOEM
base_url: /obo/mfoem

products:
- mfoem.owl: http://emotion-ontology.googlecode.com/svn/trunk/ontology/MFOEM.owl

term_browser: ontobee
example_terms:
- MFOEM_000009

entries:
- exact: /internal/neuroanno-gen.owl
  replacement: http://emotion-ontology.googlecode.com/svn/trunk/ontology/internal/neuroanno-gen.owl

- exact: /external/PATO_imported.owl
  replacement: http://emotion-ontology.googlecode.com/svn/trunk/ontology/external/PATO_imported.owl

- exact: /internal/neuroanno.owl
  replacement: http://emotion-ontology.googlecode.com/svn/trunk/ontology/internal/neuroanno.owl

- exact: /internal/em-cogpo-mapping.owl
  replacement: http://emotion-ontology.googlecode.com/svn/trunk/ontology/internal/em-cogpo-mapping.owl

- exact: /internal/em-cogatlas-mapping.owl
  replacement: http://emotion-ontology.googlecode.com/svn/trunk/ontology/internal/em-cogatlas-mapping.owl
