# PURL configuration for http://purl.obolibrary.org/obo/mondo

idspace: MONDO
base_url: /obo/mondo

products:
- mondo.owl: https://github.com/monarch-initiative/mondo/releases/download/current/mondo.owl
- mondo.obo: https://github.com/monarch-initiative/mondo/releases/download/current/mondo.obo
- mondo.json: https://github.com/monarch-initiative/mondo/releases/download/current/mondo.json

term_browser: ontobee

entries:
- prefix: /subsets/
  replacement: https://github.com/monarch-initiative/mondo/releases/download/current/
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/imports/
- prefix: /components/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/components/
- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/patterns/dosdp-patterns/
- prefix: /sparql/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/sparql/
- prefix: /reports/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/reports/
- prefix: /releases/
  replacement: https://github.com/monarch-initiative/mondo/releases/download/v
- prefix: /
  replacement: https://github.com/monarch-initiative/mondo/releases/download/current/  

