# PURL configuration for http://purl.obolibrary.org/obo/mondo

idspace: MONDO
base_url: /obo/mondo

products:
- mondo.owl: https://osf.io/bqpjm/download
- mondo.obo: https://osf.io/e87hn/download
- mondo.json: https://osf.io/pbq3a/download

term_browser: ontobee

entries:
- exact: /mondo-base.owl
  replacement: https://osf.io/5c6ky/download
- exact: /subsets/mondo-minimal.owl
  replacement: https://osf.io/8avz5/download
- exact: /subsets/mondo-minimal.obo
  replacement: https://osf.io/heu72/download
- exact: /subsets/mondo-minimal.json
  replacement: https://osf.io/6c8nk/download
- exact: /pre/mondo.obo
  replacement: https://osf.io/4c9qp/download
- exact: /pre/mondo.json
  replacement: https://osf.io/wdnyu/download
- exact: /pre/mondo.owl
  replacement: https://osf.io/ysg2b/download
- exact: /extid/mondo.obo
  replacement: https://osf.io/ay3hr/download
- exact: /extid/mondo.owl
  replacement: https://osf.io/jxkth/download
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/imports/
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/v

