# PURL configuration for http://purl.obolibrary.org/obo/mondo

idspace: MONDO
base_url: /obo/mondo

products:
- mondo.owl: https://github.com/monarch-initiative/mondo/releases/latest/download/mondo.owl
- mondo.obo: https://github.com/monarch-initiative/mondo/releases/latest/download/mondo.obo
- mondo.json: https://github.com/monarch-initiative/mondo/releases/latest/download/mondo.json

term_browser: ols

entries:
- prefix: /subsets/
  replacement: https://github.com/monarch-initiative/mondo/releases/latest/download/
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/imports/
- prefix: /components/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/components/
- prefix: /mappings/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/ontology/mappings/
- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/patterns/dosdp-patterns/
- prefix: /sources/mappings/
  replacement: https://github.com/monarch-initiative/mondo-ingest/releases/latest/download/
- prefix: /sources/releases/
  replacement: https://github.com/monarch-initiative/mondo-ingest/releases/download/v
  tests:
    - from: /sources/releases/2022-06-09/omim.owl
      to: https://github.com/monarch-initiative/mondo-ingest/releases/download/v2022-06-09/omim.owl
- prefix: /sources/
  replacement: https://github.com/monarch-initiative/mondo-ingest/releases/latest/download/
- prefix: /sparql/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/src/sparql/
- prefix: /reports/
  replacement: https://raw.githubusercontent.com/monarch-initiative/mondo/master/reports/
- prefix: /releases/
  replacement: https://github.com/monarch-initiative/mondo/releases/download/v
- prefix: /
  replacement: https://github.com/monarch-initiative/mondo/releases/latest/download/

