# PURL configuration for http://purl.obolibrary.org/obo/mro

idspace: MRO
base_url: /obo/mro

base_redirect: https://github.com/IEDB/MRO

products:
- mro.owl: https://raw.githubusercontent.com/IEDB/MRO/master/mro.owl

term_browser: ontobee
example_terms:
- MRO_0000012

entries:
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/IEDB/MRO/v

- exact: /2016-12-15/mro.owl
  replacement: https://raw.githubusercontent.com/IEDB/MRO/v2016-12-15/mro.owl
  
- exact: /2016-01-07/mro.owl
  replacement: https://raw.githubusercontent.com/IEDB/MRO/v2016-01-07/mro.owl
  
- prefix: /
  replacement: https://raw.githubusercontent.com/IEDB/MRO/master/
