# PURL configuration for http://purl.obolibrary.org/obo/ncbitaxon

idspace: NCBITaxon
base_url: /obo/ncbitaxon

products:
- ncbitaxon.owl: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.owl
- ncbitaxon.obo: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.obo
- ncbitaxon.json: https://zenodo.org/records/17901998/files/ncbitaxon.json?download=1
- ncbitaxon.owl.gz: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.owl.gz
- ncbitaxon.obo.gz: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.obo.gz
- ncbitaxon.json.gz: https://github.com/obophenotype/ncbitaxon/releases/latest/download/ncbitaxon.json.gz

term_browser: custom
example_terms:
- NCBITaxon_1

entries:
- prefix: /subsets/
  replacement: https://github.com/obophenotype/ncbitaxon/releases/latest/download/
- prefix: /2025-12-03/ncbitaxon.json
  replacement: https://zenodo.org/records/17901998/files/ncbitaxon.json?download=1
- prefix: /2
  replacement: https://github.com/obophenotype/ncbitaxon/releases/download/v2
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/NCBITaxon_1
    to: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_1
- prefix: /
  replacement: https://github.com/obophenotype/ncbitaxon/releases/latest/download/


