# PURL configuration for http://purl.obolibrary.org/obo/ncbitaxon

idspace: NCBITaxon
base_url: /obo/ncbitaxon

products:
- ncbitaxon.owl: http://www.berkeleybop.org/ontologies/ncbitaxon.owl
- ncbitaxon.obo: http://www.berkeleybop.org/ontologies/ncbitaxon.obo

term_browser: ontobee
example_terms:
- NCBITaxon_1

entries:
- prefix: /subsets/
  replacement: http://www.berkeleybop.org/ontologies/ncbitaxon/subsets/
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/NCBITaxon_1
    to: http://www.ontobee.org/browser/rdf.php?o=NCBITaxon&iri=http://purl.obolibrary.org/obo/NCBITaxon_1

