# PURL configuration for http://purl.obolibrary.org/obo/ncro

idspace: NCRO
base_url: /obo/ncro

# Current release. This gets updated when there is a new release
products:
- ncro.owl: https://raw.githubusercontent.com/OmniSearch/ncro/release-2015-12-10/build/ncro-all-in-one.owl

term_browser: ontobee
example_terms:
- NCRO_0000818

entries:
# These don't change

- prefix: /dev/
  replacement: http://raw.githubusercontent.com/OmniSearch/ncro/master/src/ontology/
- exact: /repository
  replacement: https://github.com/OmniSearch/ncro
- exact: /issues
  replacement: https://github.com/OmniSearch/ncro/issues
- exact: /browse
  replacement: http://purl.obolibrary.org/obo/NCRO_0004000

# translations for the releases here

- prefix: /2015-12-10/
  replacement: https://raw.githubusercontent.com/OmniSearch/ncro/release-2015-12-10/src/ontology/
