# PURL configuration for http://purl.obolibrary.org/obo/oae

idspace: OAE
base_url: /obo/oae

products:
- oae.owl: http://svn.code.sf.net/p/oae/code/trunk/src/ontology/oae.owl

term_browser: ontobee
example_terms:
- OAE_0000001

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OAE&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/OAE_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=OAE&iri=http://purl.obolibrary.org/obo/OAE_0000001

- prefix: /
  replacement: http://svn.code.sf.net/p/oae/code/trunk/src/ontology/

