# PURL configuration for http://purl.obolibrary.org/obo/obcs

id: OBCS
base_url: /obo/obcs

products:
- obcs.owl: https://raw.githubusercontent.com/obcs/obcs/master/release/20150417/obcs_merged_inferred.owl

term_browser: ontobee
example_terms:
- OBCS_0000001

entries:
- exact: /2015-04-17/obcs.owl
  replacement: https://raw.githubusercontent.com/obcs/obcs/master/release/20150417/obcs_merged_inferred.owl
