# PURL configuration for http://purl.obolibrary.org/obo/obi

id: OBI
base_url: /obo/obi

products:
- obi.owl: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi.owl
- obi.obo: http://www.berkeleybop.org/ontologies/obi.obo

term_browser: ontobee
example_terms:
- OBI_0000070

entries:
- exact: /project
  replacement: http://sw.neurocommons.org/obi-303/project.rdf

- exact: /wiki
  replacement: http://obi-ontology.org

- exact: /calendar
  replacement: http://www.google.com/calendar/embed?src=p8auq0a930und9nugj44p988e4%40group.calendar.google.com&ctz=America/New_York

- exact: /jowl
  replacement: http://jowl.ontologyonline.org/obi.html

- exact: /wiki/MinimalMetadata
  replacement: http://obi-ontology.org/page/OBI_Minimal_metadata

- exact: /tracker
  replacement: http://sourceforge.net/tracker/?group_id=177891&atid=886178

- exact: /policy/metadata
  replacement: http://obi-ontology.org/page/OBI_Minimal_metadata

- exact: /2009-11-02/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-02/merged/merged-obi.owl

- exact: /2009-11-06/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/merged/merged-obi.owl

- exact: /Technical_Reports
  replacement: http://obi-ontology.org/page/Technical_Reports

- exact: /2009-11-06/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/merged/obi.obo

- exact: /supplementary/protege-qtt-2009.zip
  replacement: http://www.stanford.edu/~sunid/OBI/Protege_3.4.2.zip

- exact: /2009-11-06/IEDB-use-case.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/branches/IEDB-use-case.owl

- exact: /2009-11-06/investigation-use-case.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2009-11-06/branches/investigation-use-case.owl

- exact: /2010-10-26/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2010-10-26/merged/merged-obi.owl

- exact: /homepage
  replacement: http://obi-ontology.org/

- exact: /report.html
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2010-10-26/merged/newClasses.html

- exact: /protege/obi.pprj
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/obsolete-protege-message.html

- exact: /protege/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/obsolete-protege-message.html

- exact: /owldoc
  replacement: http://owl.cs.manchester.ac.uk/browser/classes/830966544/?session=12cbe539878-8862-12cbe54e7be

- exact: /2011-04-20/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2011-04-20/merged/merged-obi-comments.owl

- exact: /2011-07-20/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2011-07-20/merged/merged-obi-comments.owl

- exact: /2011-12-13/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-01-18/merged/obi_woIEDB_comments.owl

- exact: /2011-12-13/obi_IEDBview.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-01-18/merged/obi_IEDBview.owl

- exact: /2012-03-29/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/merged-obi-comments.owl

- exact: /2012-03-29/obi_IEDBview.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/obi_IEDBview.owl

- exact: /2012-03-29/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-03-29/merged/merged-all_mod.obo

- exact: /2012-07-01/obi.owl
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/merged-obi-comments.owl

- exact: /2012-07-01/obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/obi_cleaned_merged_inferred.obo

- exact: /obi.obo
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2012-07-01/merged/obi_cleaned_merged_inferred.obo

- exact: /repository
  replacement: http://sourceforge.net/p/obi/code/HEAD/tree/

- exact: /2013-10-25/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi_core.owl

- exact: /2013-10-25/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi.owl

- exact: /obi_FGED.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2013-10-25/obi_FGED.owl

- exact: /2014-03-29/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-03-29/obi.owl

- exact: /2014-03-29/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-03-29/obi_core.owl

- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=OBI

- exact: /2014-08-18/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-08-18/obi.owl

- exact: /2014-08-18/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-08-18/obi_core.owl

- exact: /2014-12-03/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-12-03/obi.owl

- exact: /2014-12-03/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2014-12-03/obi_core.owl

- exact: /20140106/NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20140105/NIAID-GSC-BRC.owl

- exact: /2015-03-17/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-03-17/obi.owl

- exact: /2015-03-17/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-03-17/obi_core.owl

- exact: /2015-04-13/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-04-13/obi.owl

- exact: /2015-04-13/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-04-13/obi_core.owl

- exact: /NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20150413/NIAID-GSC-BRC.owl

- exact: /20150413/NIAID-GSC-BRC.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/NIAID-GSCID-BRC-view/20150413/NIAID-GSC-BRC.owl

- exact: /webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.1/webService.owl

- exact: /v1.1/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.1/webService.owl

- exact: /v1.0/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v1.0/webService.owl

- exact: /v0.9/webService.owl
  replacement: https://raw.githubusercontent.com/obi-webservice/OBIws/master/ontology/release/v0.9/webService.owl

- exact: /2015-09-15/obi.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi.owl

- exact: /2015-09-15/obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi_core.owl

- exact: /obi_core.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi_core.owl

- exact: /obi_IEDBview.owl
  replacement: http://svn.code.sf.net/p/obi/code/releases/2015-09-15/obi_iedb.owl

- exact: /release-notes.html
  replacement: http://obi-ontology.org/page/Releases/2015-09-15

- prefix: /repository/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/

- prefix: /dev/import/
  replacement: http://svn.code.sf.net/p/obi/code/trunk/src/ontology/branches/OntoFox_outputs/

- prefix: /branches/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/

- prefix: /protege/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/releases/2008-11-28/merged/protege/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBI&iri=http://purl.obolibrary.org/obo/

- prefix: /wiki/
  replacement: http://obi-ontology.org/page/

- prefix: /page/
  replacement: http://www.ontobee.org/browser/rdf.php?o=OBI&iri=

- prefix: /doc/
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/docs/

- prefix: /
  replacement: http://obi.svn.sourceforge.net/svnroot/obi/trunk/src/ontology/branches/

