# PURL configuration for http://purl.obolibrary.org/obo/obib

idspace: OBIB
base_url: /obo/obib

products:
- obib.owl: https://raw.githubusercontent.com/biobanking/biobanking/v2023-04-05/obib.owl
term_browser: ontobee
example_terms:
- OBIB_0000150

entries:
- exact: /2023-04-05/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/v2023-04-05/obib.owl

- exact: /2021-11-12/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/v2021-11-12/obib.owl

- exact: /2021-02-02/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20210202/obib.owl

- exact: /2019-06-20/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20190620/obib.owl

- exact: /2017-11-30/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20171130/src/obib.owl

- exact: /2017-10-12/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20171012/src/obib.owl

- exact: /2017-07-28/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20170728/src/obib.owl
  
- exact: /2017-06-27/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20170627/src/obib.owl
  
- exact: /2016-09-14/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/20160914/src/obib.owl

- exact: /2015-11-22/obib.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/master/release/20151122/obib_merged_inferred.owl

- exact: /dev/import_OBI_subset.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/master/src/imports/import_OBI_subset.owl

- exact: /dev/import_OBO.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/master/src/imports/import_OBO.owl

- exact: /dev/externalByhand.owl
  replacement: https://raw.githubusercontent.com/biobanking/biobanking/master/src/imports/externalByhand.owl
