# PURL configuration for http://purl.obolibrary.org/obo/ogg

idspace: OGG
base_url: /obo/ogg

products:
- ogg.owl: https://bitbucket.org/hegroup/ogg/raw/master/ogg-merged.owl

term_browser: ontobee
example_terms:
- OGG_0000000002

entries:
- exact: /ogg-pf.owl
  replacement: https://bitbucket.org/hegroup/ogg-pf/raw/master/ogg-pf.owl 

- exact: /ogg-mm.owl
  replacement: https://bitbucket.org/hegroup/ogg-mouse/raw/master/ogg-mm.owl

- exact: /ogg-dm.owl
  replacement: https://bitbucket.org/hegroup/ogg-dm/raw/master/ogg-dm.owl

- exact: /ogg-sc.owl
  replacement: https://bitbucket.org/hegroup/ogg-sc/raw/master/ogg-sc.owl

- exact: /ogg-dr.owl
  replacement: https://bitbucket.org/hegroup/ogg-dr/raw/master/ogg-dr.owl

- exact: /ogg-ce.owl
  replacement: https://bitbucket.org/hegroup/ogg-ce/raw/master/ogg-ce.owl

- exact: /ogg-bru.owl
  replacement: https://bitbucket.org/hegroup/ogg-bru/raw/master/ogg-bru.owl
  
- exact: /ogg-at.owl
  replacement: https://bitbucket.org/hegroup/ogg-at/raw/master/ogg-at.owl
