# PURL configuration for http://purl.obolibrary.org/obo/ons

idspace: ONS
base_url: /obo/ons

products:
- ons.owl: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/ons.owl

- ons.obo: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/ons.obo

term_browser: ontobee
example_terms:
- ONS_0000000

entries:
- exact: /ons_release_v1.0.owl
  replacement: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/Older_deprecated/ons_release_v1.0.owl

- exact: /ons_release_v1.1.owl
  replacement: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/Older_deprecated/ons_release_v1.1.owl

- exact: /ons_release_v1.0.obo
  replacement: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/Older_deprecated/ons_release_v1.1.obo
  
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/imports/ONS_imports.owl
