# PURL configuration for http://purl.obolibrary.org/obo/opl

idspace: OPL
base_url: /obo/opl

products:
- opl.owl: https://raw.githubusercontent.com/OPL-ontology/OPL/master/release/20150609/opl_inferred.owl

term_browser: ontobee
example_terms:
- OPL_0000232

entries:
- exact: /2012-09-07/opl.owl
  replacement: https://raw.githubusercontent.com/OPL-ontology/OPL/master/release/20120907/opl_inferred.owl

- exact: /2011-09-27/opl.owl
  replacement: https://raw.githubusercontent.com/OPL-ontology/OPL/master/release/20110927/opl_inferred_version_v2.0.owl

- exact: /2011-06-14/opl.owl
  replacement: https://raw.githubusercontent.com/OPL-ontology/OPL/master/release/20110614/opl_inferred_v1.0.owl

- exact: /2015-06-09/opl.owl
  replacement: https://raw.githubusercontent.com/OPL-ontology/OPL/master/release/20150609/opl_inferred.owl
