# PURL configuration for http://purl.obolibrary.org/obo/pco

id: PCO
base_url: /obo/pco

products:
- pco.owl: http://popcomm-ontology.googlecode.com/svn/releases/2014-05-22/pco_merged_inferred.owl

term_browser: ontobee
example_terms:
- PCO_0000000

entries:
- exact: /releases/2014-05-22/pco_merged.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2014-05-22/pco_merged.owl

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/

- prefix: /
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/src/
