# PURL configuration for http://purl.obolibrary.org/obo/pco

idspace: PCO
base_url: /obo/pco

products:
- pco.owl:  https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/pco.owl
- pco.obo: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/pco.obo

term_browser: ontobee
example_terms:
- PCO_0000000

entries:

- exact: /releases/2020-08-26/
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-08-26/

#Note this one has to be the full URI, because the ontology has the version IRI listed as 2020-02-13, and a partial replacement won't work:
- exact: http://purl.obolibrary.org/obo/pco/releases/2020-02-12/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2020-02-12/pco.owl  
  
- exact: /releases/2017-11-06/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2017-11-06/pco.owl
  
- exact: /releases/2017-08-16/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2017-08-16/pco.owl

- exact: /releases/2016-12-14/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2016-12-14/src/ontology/pco_merged_inferred.owl

- exact: /releases/2016-08-01/pco.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/2016-08-01/src/ontology/pco_merged_inferred.owl

- exact: /pco_merged_inferred.owl
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/src/ontology/pco_merged_inferred.owl
   
# - prefix: /releases/
#   replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/v

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/PCO?iri=http://purl.obolibrary.org/obo/
  
- prefix: /tracker/
  replacement: https://github.com/PopulationAndCommunityOntology/pco/issues

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/PopulationAndCommunityOntology/pco/master/
