# PURL configuration for http://purl.obolibrary.org/obo/pdumdv

idspace: PdumDv
base_url: /obo/pdumdv

products:
- pdumdv.owl: http://ontologies.berkeleybop.org/pdumdv.owl
- pdumdv.obo: http://ontologies.berkeleybop.org/pdumdv.obo

term_browser: ontobee
example_terms:
- PDUMDV_0001600
