# PURL configuration for http://purl.obolibrary.org/obo/plana

idspace: PLANA
base_url: /obo/plana

products:
- plana.owl: https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/plana.owl
- plana.obo: https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/plana.obo

term_browser: ontobee
example_terms:
- PLANA_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/planaria-ontology/v

- prefix: /tracker/
  replacement: https://github.com/obophenotype/planaria-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/PLANA?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/
