# PURL configuration for http://purl.obolibrary.org/obo/po

idspace: PO
base_url: /obo/po

products:
- po.owl: https://raw.githubusercontent.com/Planteome/plant-ontology/master/po.owl
- po.obo: https://raw.githubusercontent.com/Planteome/plant-ontology/master/po.obo
- subsets/po-basic.obo: https://raw.githubusercontent.com/Planteome/plant-ontology/master/subsets/po-basic.obo

term_browser: ontobee
example_terms:
- PO_0009012
