# PURL configuration for http://purl.obolibrary.org/obo/poro

idspace: PORO
base_url: /obo/poro

base_redirect: https://github.com/obophenotype/porifera-ontology

products:
- poro.owl: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/poro.owl
- poro.obo: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/poro.obo

term_browser: ols
example_terms:
- PORO_0000017

entries:
- exact: /browse
  replacement: http://www.ontobee.org/browser/index.php?o=PORO

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/porifera-ontology/v

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=PORO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/PORO_0000017
    to: https://www.ebi.ac.uk/ols/ontologies/poro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPORO_0000017

- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/porifera-ontology/master/

