# PURL configuration for http://purl.obolibrary.org/obo/pr
# Warning: the Protein Ontology also uses /obo/pro

idspace: PR
base_url: /obo/pr

base_redirect: http://proconsortium.org

products:
- pr.owl: ftp://ftp.pir.georgetown.edu/databases/ontology/pro_obo/pro.owl
- pr.obo: ftp://ftp.pir.georgetown.edu/databases/ontology/pro_obo/pro.obo

term_browser: custom

entries:
- prefix: /about/
  replacement: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=
  tests:
  - from: /about/PR_000000001
    to: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PR_000000001
