# PURL configuration for http://purl.obolibrary.org/obo/psdo

idspace: PSDO
base_url: /obo/psdo

products:
- psdo.owl: https://raw.githubusercontent.com/Display-Lab/psdo/main/psdo.owl

term_browser: ontobee
example_terms:
- PSDO_0000001

entries:

- prefix: /tracker/
  replacement: https://github.com/Display-Lab/psdo/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/PSDO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/Display-Lab/psdo/master/
