# PURL configuration for http://purl.obolibrary.org/obo/rex

idspace: REX
base_url: /obo/rex

products:
- rex.owl: http://www.berkeleybop.org/ontologies/rex.owl

term_browser: ontobee
example_terms:
- REX_0000078
