# PURL configuration for http://purl.obolibrary.org/obo/sbo

idspace: SBO
base_url: /obo/sbo

products:
- sbo.owl: http://www.berkeleybop.org/ontologies/sbo.owl
- sbo.obo: http://www.berkeleybop.org/ontologies/sbo.obo

term_browser: ontobee
example_terms:
- SBO_0000000
