# PURL configuration for http://purl.obolibrary.org/obo/sep

idspace: sep
base_url: /obo/sep

products:
- sep.owl: http://www.berkeleybop.org/ontologies/sep.owl
- sep.obo: http://www.berkeleybop.org/ontologies/sep.obo

term_browser: ontobee
example_terms:
- sep_00073
