# PURL configuration for http://purl.obolibrary.org/obo/sibo

idspace: SIBO
base_url: /obo/sibo

products:
- sibo.owl: https://raw.githubusercontent.com/obophenotype/sibo/master/sibo.owl
- sibo.owl: https://raw.githubusercontent.com/obophenotype/sibo/master/sibo.obo 

term_browser: ontobee
example_terms:
- SIBO_0000000
