# PURL configuration for http://purl.obolibrary.org/obo/spd

idspace: SPD
base_url: /obo/spd

products:
- spd.owl: http://www.berkeleybop.org/ontologies/spd.owl
- spd.obo: http://www.berkeleybop.org/ontologies/spd.obo

term_browser: ontobee
example_terms:
- SPD_0000000
