# PURL configuration for http://purl.obolibrary.org/obo/stato

id: STATO
base_url: /obo/stato

products:
- stato.owl: https://raw.githubusercontent.com/ISA-tools/stato/dev/releases/1.2/stato.owl

term_browser: ontobee
example_terms:
- STATO_0000001
