# PURL configuration for http://purl.obolibrary.org/obo/swo

idspace: SWO
base_url: /obo/swo

products:
- swo.owl: https://raw.githubusercontent.com/allysonlister/swo/master/swo.owl
- swo.json: https://raw.githubusercontent.com/allysonlister/swo/master/swo.json

term_browser: ols
example_terms:
- SWO_0000000

entries:
- prefix: /tracker/
  replacement: https://github.com/allysonlister/swo/issues
