# PURL configuration for http://purl.obolibrary.org/obo/tao

id: TAO
base_url: /obo/tao

products:
- tao.owl: http://svn.code.sf.net/p/phenoscape/code/tags/vocab-releases/TAO/tao.owl
- tao.obo: http://svn.code.sf.net/p/phenoscape/code/tags/vocab-releases/TAO/tao.obo

term_browser: ontobee
example_terms:
- TAO_0000079

entries:
- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=TAO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/TAO_0000079
    to: http://www.ontobee.org/browser/rdf.php?o=TAO&iri=http://purl.obolibrary.org/obo/TAO_0000079

- prefix: /
  replacement: http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/tags/vocab-releases/TAO/

