# PURL configuration for http://purl.obolibrary.org/obo/to

idspace: TO
base_url: /obo/to

products:
- to.owl: https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/to.owl
- to.obo: https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/to.obo

term_browser: ontobee
example_terms:
- TO_0000001

entries:
- exact: /termgenie
  replacement: http://to.termgenie.org

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/Planteome/plant-trait-ontology/v

- prefix: /ibp-cassava-traits/
  replacement: https://raw.githubusercontent.com/Planteome/ibp-cassava-traits/master/

- prefix: /ibp-lentil-traits/
  replacement: https://raw.githubusercontent.com/Planteome/ibp-lentil-traits/master/

- prefix: /ibp-rice-traits/
  replacement: https://raw.githubusercontent.com/Planteome/ibp-rice-traits/master/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=TO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/TO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=TO&iri=http://purl.obolibrary.org/obo/TO_0000001

- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/patterns/
    
- prefix: /
  replacement: https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/

