# PURL configuration for http://purl.obolibrary.org/obo/upheno

idspace: UPHENO
base_url: /obo/upheno

products:
- upheno.owl: https://github.com/obophenotype/upheno-dev/releases/latest/download/upheno.owl

term_browser: ontobee
example_terms:
- UPHENO_0000000

entries:
- exact: /monarch.owl
  replacement: https://raw.githubusercontent.com/monarch-initiative/monarch-ontology/master/monarch.owl

- exact: /doid/bridge.owl
  replacement: https://raw.githubusercontent.com/monarch-initiative/monarch-disease-ontology/master/src/mondo/bridge.owl

- exact: /doid/mondo.owl
  replacement: https://raw.githubusercontent.com/monarch-initiative/monarch-disease-ontology/master/src/mondo/mondo.owl

- exact: /v2/upheno.owl
  replacement: https://github.com/obophenotype/upheno-dev/releases/latest/download/upheno.owl

- exact: /zp.owl
  replacement: http://purl.obolibrary.org/obo/zp.owl

- exact: /mp-hp-view.owl
  replacement: http://build-artifacts.berkeleybop.org/build-mp-hp-view/latest/mp-hp-view.owl

- exact: /mappings/mp-hp.csv
  replacement: https://raw.githubusercontent.com/obophenotype/upheno-dev/master/mappings/upheno_mapping_mp_hp.csv

- prefix: /mondo/gard/
  replacement: https://raw.githubusercontent.com/monarch-initiative/monarch-disease-ontology/master/src/gard/
- prefix: /patterns/
  replacement: https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-patterns/
- prefix: /patterns-dev/
  replacement: https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/
- prefix: /data/
  replacement: http://build.berkeleybop.org/view/Monarch/job/generate-triples-from-nif/lastSuccessfulBuild/artifact/target/
- prefix: /imports/
  replacement: https://raw.githubusercontent.com/obophenotype/upheno/master/imports/
- prefix: /v2/
  replacement: https://bbop-ontologies.s3.amazonaws.com/upheno/current/upheno-release/all/
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/upheno/master/

