# PURL configuration for http://purl.obolibrary.org/obo/vo

idspace: VO
base_url: /obo/vo

base_redirect: https://github.com/vaccineontology/VO

products:
- vo.owl: https://raw.githubusercontent.com/vaccineontology/VO/master/vo.owl

term_browser: ontobee
example_terms:
- VO_0000001
- VO_0000002

entries:
- exact: /tracker
  replacement: https://github.com/vaccineontology/VO/issues

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/vaccineontology/VO/v

- exact: /cvo.owl
  replacement: https://raw.githubusercontent.com/vaccineontology/VO/master/CVO/cvo.owl

- prefix: /external/
  replacement: https://raw.githubusercontent.com/vaccineontology/VO/master/src/

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=VO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/VO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=VO&iri=http://purl.obolibrary.org/obo/VO_0000001

- prefix: /page/
  replacement: http://www.ontobee.org/browser/about.php?o=VO&iri=http://purl.obolibrary.org/obo/

- exact: /
  replacement: http://www.violinet.org/vaccineontology/

### Dated VO Releases
- exact: /2024-01-03/vo.owl
  replacement: https://raw.githubusercontent.com/vaccineontology/VO/v2024-01-03/vo.owl



