# PURL configuration for http://purl.obolibrary.org/obo/vto

idspace: VTO
base_url: /obo/vto

products:
- vto.owl: http://vertebrate-taxonomy-ontology.googlecode.com/svn/trunk/releases/vto.owl
- vto.obo: http://vertebrate-taxonomy-ontology.googlecode.com/svn/trunk/releases/vto.obo

term_browser: ontobee
example_terms:
- VTO_0000001

entries:
- exact: /tracker
  replacement: http://code.google.com/p/vertebrate-taxonomy-ontology/issues/list

- prefix: /about/
  replacement: http://www.ontobee.org/browser/rdf.php?o=VTO&iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/VTO_0000001
    to: http://www.ontobee.org/browser/rdf.php?o=VTO&iri=http://purl.obolibrary.org/obo/VTO_0000001

- prefix: /
  replacement: http://vertebrate-taxonomy-ontology.googlecode.com/svn/trunk/releases/

