# PURL configuration for http://purl.obolibrary.org/obo/wbphenotype

idspace: WBPhenotype
base_url: /obo/wbphenotype

products:
- wbphenotype.owl: https://raw.githubusercontent.com/obophenotype/c-elegans-phenotype-ontology/master/wbphenotype.owl
- wbphenotype.obo: https://raw.githubusercontent.com/obophenotype/c-elegans-phenotype-ontology/master/wbphenotype.obo

term_browser: ontobee
example_terms:
- WBPhenotype_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/c-elegans-phenotype-ontology/v

- prefix: /tracker/
  replacement: https://github.com/obophenotype/c-elegans-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/WBPhenotype?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/c-elegans-phenotype-ontology/master/
