# PURL configuration for http://purl.obolibrary.org/obo/xao

idspace: XAO
base_url: /obo/xao

products:
- xao.owl: http://ontologies.berkeleybop.org/xao.owl
- xao.obo: http://ontologies.berkeleybop.org/xao.obo

term_browser: ontobee

entries:
- prefix: /tracker/
  replacement: https://sourceforge.net/tracker/?func=detail&group_id=76834&atid=1127722&aid=

