# PURL configuration for http://purl.obolibrary.org/obo/xpo

idspace: XPO
base_url: /obo/xpo

products:
- xpo.owl: https://raw.githubusercontent.com/obophenotype/xenopus-phenotype-ontology/master/xpo.owl
- xpo.obo: https://raw.githubusercontent.com/obophenotype/xenopus-phenotype-ontology/master/xpo.obo

term_browser: ontobee
example_terms:
- XPO_0000000

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/xenopus-phenotype-ontology/v

- prefix: /tracker/
  replacement: https://github.com/obophenotype/xenopus-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/XPO?iri=http://purl.obolibrary.org/obo/

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/xenopus-phenotype-ontology/master/
