# PURL configuration for http://purl.obolibrary.org/obo/zeco

idspace: ZECO
base_url: /obo/zeco

products:
- zeco.owl: https://raw.githubusercontent.com/ybradford/zebrafish-experimental-conditions-ontology/master/zeco.owl
- zeco.obo: https://raw.githubusercontent.com/ybradford/zebrafish-experimental-conditions-ontology/master/zeco.obo
- zeco.json: https://raw.githubusercontent.com/ybradford/zebrafish-experimental-conditions-ontology/master/zeco.json

term_browser: ontobee
example_terms:
- ZECO_00000001

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/ybradford/zeco/master/v
