# PURL configuration for http://purl.obolibrary.org/obo/zp

idspace: ZP
base_url: /obo/zp

products:
- zp.owl: https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/download/current/zp.owl
- zp.obo: https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/download/current/zp.obo

term_browser: ontobee
example_terms:
- ZP_0000000

entries:

- prefix: /releases/
  replacement: https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/download/v

- prefix: /tracker/
  replacement: https://github.com/obophenotype/zebrafish-phenotype-ontology/issues

- prefix: /about/
  replacement: http://www.ontobee.org/ontology/ZP?iri=http://purl.obolibrary.org/obo/

- prefix: /
  replacement: https://github.com/obophenotype/zebrafish-phenotype-ontology/releases/download/current/
